@startuml
'https://plantuml.com/sequence-diagram

autonumber

JobApiController -> AdminBizImpl: registry
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml